export const CLINIC_DATA = {
  phoneMobile: "+505 8874-4524",
  phoneDisplayMobile: "+505 8874-4524",
  phoneLandline: "+505 2341-1625",
  whatsappBaseUrl: "https://wa.me/50588744524",
  instagramUrl: "https://www.instagram.com/dra.gabrielapereiracoen",
  facebookUrl: "https://www.facebook.com/share/18mn7r5t8Y/",
};

export type LanguageType = "en" | "es";

export const NAV_LINKS = [
  { id: "about", en: "The Doctor", es: "La Doctora" },
  { id: "services", en: "Treatments", es: "Tratamientos" },
  { id: "faq", en: "Patient FAQ", es: "Preguntas Frecuentes" },
  { id: "appointment-intake", en: "Contact Us", es: "Contacto" }
];

export const DICTIONARY = {
  en: {
    nav: { contact: "Book Appointment" },
    productsBadge: {
      tag: "PREMIUM DENTAL KITS",
      title: "Professional Oral Care Essentials",
      desc: "Acquire recommended specialized clinical brushes and personalized hygiene kits directly at our office during your appointment to maintain your radiant smile."
    },
    hero: {
      tag: "CHINANDEGA, NICARAGUA • EXCELLENCE IN ORAL HEALTH",
      headline: "Smiles Crafted with Real Care & Precision.",
      subheadline: "Welcome to your premier dental health clinic in Chinandega. Led by specialized endodontist Dr. Gabriela Pereira Coen, we combine advanced modern care with a gentle touch to safeguard your family's smiles.",
      cta: "Book via WhatsApp",
      whatsappMessage: "https://wa.me/50588744524?text=Hello%20Dr.%20Gabriela%2C%20I%20would%20like%20to%20request%20a%20dental%20consultation%20appointment.",
      socialSubtext: "Browse our diagnostic cases and real patient smile transformations on Instagram and Facebook.",
    },
    trust: {
      text: "Trusted dental care for families across Chinandega.",
      m1: "Premium Clinical Facilities",
      m2: "Highly Recommended by Our Community",
      m3: "Certified Dentistry & Care",
    },
    about: {
      tag: "SPECIALIZED DENTIST",
      heading: "Meet Dr. Gabriela Pereira Coen",
      body: "Hello! I am Dr. Gabriela Pereira Coen, a certified Dental Surgeon graduated from UNAN-León, with specialized postgraduate training in Endodontics from UAM. My mission is to make your dental care completely transparent, comfortable, and stress-free. I believe in honest evaluations, meticulous cleanings, and clear communication so you always know exactly how we are protecting your smile.",
    },
    services: {
      tag: "OUR TREATMENTS",
      title: "Our Dental Treatments.",
      subtitle: "Comprehensive, delicate dental treatments personalized to protect your enamel and long-term health.",
      s1_title: "Specialized Root Canals",
      s1_desc: "Advanced, comfortable endodontic treatments to eliminate localized pain and safely preserve your natural tooth anatomy.",
      s2_title: "Preventative Oral Hygiene",
      s2_desc: "Professional deep scaling, surface stain removal, and thorough early stage cavity tracking.",
      s3_title: "Cosmetic Smile Makeovers",
      s3_desc: "Premium office whitening procedures and delicate custom veneers designed to completely refresh your confidence.",
      s4_title: "Restorations & Crowns",
      s4_desc: "High-density aesthetic resin fillings and durable porcelain crowns to seamlessly rebuild damaged teeth.",
      s5_title: "Complete Family Dentistry",
      s5_desc: "Patient, exceptionally warm dental care tailored to make children, teens, and adults feel safe in the chair.",
      s6_title: "Hygiene Product Boutique",
      s6_desc: "Direct access to premium, medical-grade toothbrushes and specialized clinical rinses stocked right here in our office.",
    },
    faq: {
      tag: "HELPFUL INFORMATION",
      title: "Frequently Asked Questions.",
      q1: "Where is the dental clinic located?",
      a1: "Our practice is conveniently located in Chinandega, from INISER, half a block South.",
      q2: "Do I need an appointment or do you accept walk-ins?",
      a2: "To ensure every patient gets our undivided clinical attention, we operate entirely by scheduled appointments. The easiest way to secure your day is by dropping us a text on WhatsApp.",
      q3: "Is a root canal procedure painful?",
      a3: "No. With modern localized numbing techniques, our specialized endodontic procedures are entirely comfortable. They are designed to instantly remove internal tooth infection and stop severe toothaches.",
      q4: "When should children have their first dental visit?",
      a4: "We recommend scheduling their primary checkup by their first birthday to establish positive tracking trends in a friendly, completely stress-free setting.",
      q5: "Can I buy specialty hygiene products directly at the office?",
      a5: "Yes, absolutely! We keep a curated inventory of clinical-grade brushes and treatment rinses recommended directly by Dr. Gabriela so you don't have to make an extra stop at the pharmacy.",
    },
    form: {
      heading: "Request a Dental Consultation",
      nameLabel: "Your Full Name",
      phoneLabel: "WhatsApp / Contact Phone",
      descLabel: "Describe Your Dental Goals or Symptoms (Optional)",
      descPlaceholder: "Example: Cold sensitivity, interested in a whitening session, routine cleanup check...",
      submitBtn: "Schedule My Free Consultation",
      success: "Thank you. Your request is safely received, and our friendly dental care team will message your WhatsApp line very shortly.",
    },
    footer: {
      addressLabel: "Clinic Location",
      addressValue: "De INISER, 1/2 block South, Chinandega, Nicaragua.",
      hoursLabel: "Clinic Hours",
      h1: "Monday to Friday: 8:00 AM – 5:00 PM",
      h2: "Saturday: 8:00 AM – 12:00 PM",
      h3: "Sunday: Closed",
      linksLabel: "Connect With Us",
      instagram: "Follow on Instagram",
      facebook: "Connect on Facebook",
    },
  },
  es: {
    nav: { contact: "Agendá tu Cita" },
    productsBadge: {
      tag: "CUIDADO EXCLUSIVO",
      title: "Kits Profesionales de Higiene Bucal",
      desc: "Mantené una sonrisa impecable con cepillos de alta especialidad e hilos bucales indicados personalmente por la odontóloga en nuestra consulta."
    },
    hero: {
      tag: "CHINANDEGA, NICARAGUA • EXCELENCIA EN SALUD BUCAL",
      headline: "Sonrisas Creadas con Verdadero Cuidado y Precisión.",
      subheadline: "Bienvenidos a tu clínica dental de confianza en Chinandega. Bajo la dirección de la Dra. Gabriela Pereira Coen, especialista en endodoncia, combinamos técnicas modernas avanzadas con un trato humano y delicado para cuidar el bienestar de toda tu familia.",
      cta: "Agendá por WhatsApp",
      whatsappMessage: "https://wa.me/50588744524?text=Hola%20Dra.%20Gabriela%2C%20me%20gustar%C3%ADa%20solicitar%20una%20cita%20para%20una%20consulta%20dental.",
      socialSubtext: "Explorá nuestros casos de éxito y transformaciones de sonrisas reales en Instagram y Facebook.",
    },
    trust: {
      text: "Cuidado dental de confianza para las familias de Chinandega.",
      m1: "Consultorio Clínico Premium",
      m2: "Recomendado por la Comunidad",
      m3: "Odontología y Restauraciones Certificadas",
    },
    about: {
      tag: "ODONTÓLOGA ESPECIALISTA",
      heading: "Conocé a la Dra. Gabriela Pereira Coen",
      body: "¡Hola! Soy la Dra. Gabriela Pereira Coen, Cirujano Dentista egresada de la prestigiosa UNAN-León, con estudios de postgrado en Endodoncia por la UAM. Mi misión es brindarte una atención dental completamente transparente, cómoda y libre de estrés. Creo firmemente en las evaluaciones honestas, las limpiezas meticulosas y una comunicación clara para que siempre sepás cómo protegemos tu sonrisa.",
    },
    services: {
      tag: "NUESTROS TRATAMIENTOS",
      title: "Nuestros Tratamientos Odontológicos.",
      subtitle: "Procedimientos integrales y sumamente delicados, personalizados para proteger tu esmalte y salud a largo plazo.",
      s1_title: "Endodoncias Especializadas",
      s1_desc: "Tratamientos de conductos avanzados y muy cómodos para eliminar dolores severos y conservar la anatomía de tu diente natural.",
      s2_title: "Higiene Dental Preventiva",
      s2_desc: "Limpiezas profundas con eliminación de sarro y manchas rebeldes junto a un diagnóstico oportuno para prevenir caries.",
      s3_title: "Estética Bucal y Blanqueamiento",
      s3_desc: "Aclaramiento dental profesional en el consultorio y carillas finas diseñadas a medida para renovar por completo tu confianza.",
      s4_title: "Restauraciones y Coronas",
      s4_desc: "Calzas estéticas de resina premium y coronas cerámicas altamente duraderas para reconstruir con precisión dientes dañados.",
      s5_title: "Odontología Familiar Completa",
      s5_desc: "Atención pacífica, empática y sumamente cariñosa diseñada para que niños, jóvenes y adultos se sientan plenamente seguros en la silla.",
      s6_title: "Boutique de Cuidado Dental",
      s6_desc: "Adquirí cepillos clínicos de alta gama e hilos o enjuagues específicos indicados por la doctora directamente en nuestras instalaciones.",
    },
    faq: {
      tag: "INFORMACIÓN DE UTILIDAD",
      title: "Preguntas Frecuentes.",
      q1: "¿Dónde está ubicada exactamente la clínica?",
      a1: "Nuestra clínica se encuentra en Chinandega, de INISER, media cuadra al Sur.",
      q2: "¿Atienden emergencias o es obligatorio agendar cita?",
      a2: "Para asegurar que cada paciente reciba el tiempo exclusivo y la atención diagnóstica que te merecés, trabajamos únicamente con previa cita. Agendá fácilmente mandándonos un mensaje por WhatsApp.",
      q3: "¿Es doloroso hacerse una endodoncia?",
      a3: "Para nada. Con las modernas técnicas de anestesia local, nuestros tratamientos de conductos son sumamente confortables. Están diseñados para aliviar dolores severos generados por infecciones internas de inmediato.",
      q4: "¿Cuándo deben los niños tener su primera visita al dentista?",
      a4: "Recomendamos programar su primera revisión al cumplir su primer año de edad. Esto ayuda a iniciar un control preventivo positivo en un amigable ambiente y libre de tensiones.",
      q5: "¿Puedo comprar productos especializados directo en el consultorio?",
      a5: "¡Por supuesto que sí! Mantenemos una selección exclusiva de cepillos de alta especialidad y pastas o enjuagues clínicos recomendados directamente por la Dra. Gabriela, evitándote paradas extra en la farmacia.",
    },
    form: {
      heading: "Solicitá tu Consulta Dental",
      nameLabel: "Tu Nombre Completo",
      phoneLabel: "Número de Teléfono / WhatsApp",
      descLabel: "Describí Brevemente tus Síntomas o Metas (Opcional)",
      descPlaceholder: "Ejemplo: Sensibilidad al frío, interés en blanqueamiento o limpieza dental de rutina...",
      submitBtn: "Enviá tu Solicitud de Cita",
      success: "Muchas gracias. Recibimos tus datos de forma segura. Nuestro equipo se comunicará con vos por WhatsApp a la brevedad.",
    },
    footer: {
      addressLabel: "Dirección de la Clínica",
      addressValue: "De INISER, 1/2 cuadra al Sur, Chinandega, Nicaragua.",
      hoursLabel: "Horas de Atención",
      h1: "Lunes a Viernes: 8:00 AM – 5:00 PM",
      h2: "Sábado: 8:00 AM – 12:00 MD",
      h3: "Domingo: Cerrado",
      linksLabel: "Conectá Con Nosotros",
      instagram: "Seguinos en Instagram",
      facebook: "Conectate en Facebook",
    },
  },
};
